---
version: '3'
services:
  submit-connectors-queries:
    build: kafka-connect/connector-builder
    hostname: submit-connectors-queries
    container_name: submit-connectors-queries
    depends_on:
      connect:
        condition: service_healthy
      ksqldb-server:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
      - ./kafka-connect/connectors:/connectors
      - ./ksqlDB/queries:/queries
      - ./topics:/topics
      - ./sentiment-analysis/python-cp/avro:/schemas
    environment:
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
    command:
      - bash
      - -c
      - |
        for topic in /topics/*.txt; do /scripts/submit-topic.sh $${topic} broker:29092; done
        for schema in /schemas/*.avsc; do /scripts/submit-schema.sh $${schema} schema-registry:8081; done
        for connector in /connectors/*.json; do /scripts/submit-connector.sh $${connector} connect; done
        sleep 30
        for query in /queries/*.ksql; do /scripts/submit-stored-queries.sh $${query} ksqldb-server; done